---
###############################################################################
#                           Authelia Configuration                            #
#                        Access Control Configuration                         #
###############################################################################

## Access Control Configuration
##
## Access control is a list of rules defining the authorizations applied for one resource to users or group of users.
##
## If 'access_control' is not defined, ACL rules are disabled and the 'bypass' rule is applied, i.e., access is allowed
## to anyone. Otherwise restrictions follow the rules defined.
##
## Note: One can use the wildcard * to match any subdomain.
## It must stand at the beginning of the pattern. (example: *.mydomain.com)
##
## Note: You must put patterns containing wildcards between simple quotes for the YAML to be syntactically correct.
##
## Definition: A 'rule' is an object with the following keys: 'domain', 'subject', 'policy' and 'resources'.
##
## - 'domain' defines which domain or set of domains the rule applies to.
##
## - 'subject' defines the subject to apply authorizations to. This parameter is optional and matching any user if not
##    provided. If provided, the parameter represents either a user or a group. It should be of the form
##    'user:<username>' or 'group:<groupname>'.
##
## - 'policy' is the policy to apply to resources. It must be either 'bypass', 'one_factor', 'two_factor' or 'deny'.
##
## - 'resources' is a list of regular expressions that matches a set of resources to apply the policy to. This parameter
##   is optional and matches any resource if not provided.
##
## Note: the order of the rules is important. The first policy matching (domain, resource, subject) applies.

access_control:
  default_policy: deny
  networks:
  - name: tailscale
    networks:
    - '10.20.0.0/24'
  - name: cloudflare
    networks:
    - '172.20.0.0/24'
  rules:
  ## Tailscale protected path example
    - domain: 'my-tailscale.ts.net'
      policy: bypass
      networks:
      - tailscale
      subject:
      - ['group:admin', 'group:tailscale']
    - domain: 'my-tailscale.ts.net'
      policy: one_factor
      networks:
      - tailscale


  ## Cloudflare protected path example
    - domain: 'pwd.example.com'
      resources:
        - '^/admin([/?].*)?$'
      policy: two_factor
    - domain: 'pwd.example.com'
      policy: bypass

  ## Cloudflare domain example
    - domain:
      - 'towfactor.example.com'
      policy: two_factor
    
    - domain:
      - 'onefactor.example.com'
      policy: 'one_factor'

    - domain:
      - 'bypass.example.com'
      policy: bypass

...
