---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.
## hash pass : docker run --rm authelia/authelia:latest authelia hash-password -- ThisIs1ExamplePass

# List of users
users:
  admin:
    displayname: "Admin"
    password: "$argon2id$v=19$m=65536,t=3,p=4$PJCfh2JBSxUmRFf2OzFpYQ$gZ81utWnkblKbeIsbsTYdDnsFnBg4f2TlpPKJazZVwg"
    email: admin@example.com
    groups:
      - admins
      - tailscale
...