---
###############################################################################
#                                 Authelia                                    #
#                           General Configuration                             #
###############################################################################

theme: dark

default_redirection_url: https://example.com/auth # This is the URL that Authelia will redirect to after a successful login.

default_2fa_method: ""

server:
  host: 0.0.0.0
  port: 9091
  path: "/auth"
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  buffers:
    read: 10485760 # 10MB
    write: 10485760 # 10MB
  timeouts:
    read: 6s
    write: 6s
    idle: 30s

log:
  level: info
  format: json

telemetry:
  metrics:
    enabled: false
    address: tcp://0.0.0.0:9959

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

webauthn:
  disable: false
  timeout: 60s
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred

duo_api:
  disable: false
  hostname: api-XXXX-example.com
  integration_key: EXAMPLE
  # secret_key: IN FILE
  enable_self_enrollment: false

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
    custom_url: ""
  refresh_interval: 5m
  file:
    path: /config/local_users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 512
      parallelism: 8

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

session:
  name: authelia_session
  domain: example.com
  same_site: lax
  # secret: IN FILE
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 3M
  redis:
    host: local-authelia-redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  # encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  # local:
  #   path: /config/db.sqlite3
  postgres:
    host: local-authelia-postgres
    port: 5432
    database: authelia_db
    schema: public
    username: authelia_user
    ## Password can also be set using a secret: https://www.authelia.com/c/secrets
    # password: IN FILE
    timeout: 5s
    ssl:
      mode: disable
      root_certificate: disable
      certificate: disable
      key: disable
...